name: gh
on:
  push:
jobs:
  gh:
    runs-on: ubuntu-20.04
    concurrency:
      group: gh
      cancel-in-progress: false
    env:
      GIT_COMMITTER_NAME: GitHub Action
      GIT_AUTHOR_NAME: GitHub Action
      EMAIL: action@github.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: gh auth setup-git
      - run: pip install numpy
      - run: python3 workflow.py
